### ISSUE TITLE
Should we use a database instead of logfile?

### ISSUE THREAD

**Issue by reboss** [reboss/CCAT#25]
After really thinking about it, although there will never be that much data stored in the database and it might seem like a waste of resources, it would still be a good idea to use a database instead of a log file.  It will simplify the build process because it looks as though JARs are more compatible with databases than file i/o 

To be clear the database will be used to store admin data, questions to be displayed on the audit form and all the saved output of the audits.

**Comment by ElliottSobek** [comment]
How will the database, sql variant?, communicate with the program after the build? Will the database be packaged with the project?

**Comment by reboss** [comment]
If we use SQLite, apparently it can be packaged with the jar.  We could also use mySQL and then just build the database on the hospitals machine when we install the jar.

We'd connect and communicate with the database using something like what's described in <a href="http://stackoverflow.com/questions/25651641/javafx-mysql-connection-example-please">this thread</a>

**Comment by ElliottSobek** [comment]
I believe SQLite would be the best method of storing data as it is a single file database. SQLite should be fairly easy to implement to CCAT.
